[project]
name = "pyaddict"
version = "2.0.0"
description = "yet another dict library"
readme = "README.md"
authors = [
    { name = "davidohnee", email = "dxstiny.gh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.urls]
Homepage = "https://github.com/davidohnee/pyaddict"
Documentation = "https://github.com/davidohnee/pyaddict/wiki"
Repository = "https://github.com/davidohnee/pyaddict.git"
Issues = "https://github.com/davidohnee/pyaddict/issues"
Changelog = "https://github.com/davidohnee/pyaddict/blob/main/CHANGELOG.md"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
lint = [
    "ruff>=0.15.20",
    "ty>=0.0.56",
]

[tool.ruff]
fix = true
lint.select = ["B", "D", "DOC", "E", "F", "N", "Q", "PYI"]
lint.ignore = ["DOC502", "D212", "D211"]

[tool.ruff.lint.per-file-ignores]
"**/test*.py" = ["D"]
